// flow-typed signature: 63f41b55154c6ebb86ca2419eebf2e65
// flow-typed version: <<STUB>>/@reach/portal_v^0.18.0/flow_v0.193.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reach/portal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reach/portal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reach/portal/dist/reach-portal.cjs.dev' {
  declare module.exports: any;
}

declare module '@reach/portal/dist/reach-portal.cjs' {
  declare module.exports: any;
}

declare module '@reach/portal/dist/reach-portal.cjs.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reach/portal/dist/reach-portal.cjs.dev.js' {
  declare module.exports: $Exports<'@reach/portal/dist/reach-portal.cjs.dev'>;
}
declare module '@reach/portal/dist/reach-portal.cjs.js' {
  declare module.exports: $Exports<'@reach/portal/dist/reach-portal.cjs'>;
}
declare module '@reach/portal/dist/reach-portal.cjs.prod.js' {
  declare module.exports: $Exports<'@reach/portal/dist/reach-portal.cjs.prod'>;
}
